In [1]:
!pip install keras

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
###sentences
sent=[
    'the glass of milk',
    'the cup of tea',
    'I am a good boy',
    'I am a ggood developer',
    'underrstand the meaning of words',
    'your videos are good'
]

In [6]:
sent

['the glass of milk',
 'the cup of tea',
 'I am a good boy',
 'I am a ggood developer',
 'underrstand the meaning of words',
 'your videos are good']

In [7]:
#define vocabulary size
voc_size=10000

In [8]:
### obne hot representaation
one_hot_representation=[one_hot(words,voc_size)for words in sent]
one_hot_representation
                               

[[8720, 3907, 6162, 6802],
 [8720, 9297, 6162, 5532],
 [9672, 9907, 1444, 3120, 6959],
 [9672, 9907, 1444, 1287, 9458],
 [1348, 8720, 9638, 6162, 9246],
 [5099, 2911, 6858, 3120]]

In [9]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
emmbedded_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(emmbedded_docs)

[[   0    0    0    0 8720 3907 6162 6802]
 [   0    0    0    0 8720 9297 6162 5532]
 [   0    0    0 9672 9907 1444 3120 6959]
 [   0    0    0 9672 9907 1444 1287 9458]
 [   0    0    0 1348 8720 9638 6162 9246]
 [   0    0    0    0 5099 2911 6858 3120]]


In [12]:
##feartures dimension
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\ANURAG RAWAT\anaconda3\envs\arnav\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(emmbedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step


array([[[-0.02064166, -0.01310875,  0.03672225, -0.01155061,
         -0.0289869 , -0.03334177, -0.04163992, -0.04770128,
         -0.02381376,  0.01244167],
        [-0.02064166, -0.01310875,  0.03672225, -0.01155061,
         -0.0289869 , -0.03334177, -0.04163992, -0.04770128,
         -0.02381376,  0.01244167],
        [-0.02064166, -0.01310875,  0.03672225, -0.01155061,
         -0.0289869 , -0.03334177, -0.04163992, -0.04770128,
         -0.02381376,  0.01244167],
        [-0.02064166, -0.01310875,  0.03672225, -0.01155061,
         -0.0289869 , -0.03334177, -0.04163992, -0.04770128,
         -0.02381376,  0.01244167],
        [-0.03809176,  0.03860095, -0.0121451 , -0.01416608,
          0.01338749,  0.04353324,  0.04591987,  0.03904862,
          0.01016656, -0.02365627],
        [ 0.02142847,  0.03260725,  0.04446305,  0.02427967,
          0.02144431,  0.02910054,  0.03791321,  0.02117405,
          0.03344233, -0.03049721],
        [ 0.01392836,  0.03951028, -0.02093328,  0.0